language: node_js
node_js:
  - "4.5.0"
  - "6.4.0"
sudo: false
script:
- node bin/ci.js
env:
  matrix:
  - TEST_TYPE=lint_and_test_unit
  - TEST_TYPE=integration_test
  - TEST_TYPE=test_create_project
cache:
  directories:
    - node_modules
