language: node_js
node_js:
- 6.9.2
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash # until yarn is
- export PATH=$HOME/.yarn/bin:$PATH                 # pre-installed
script:
- node bin/ci.js
env:
  matrix:
  - TEST_TYPE=integration_test
cache:
  directories:
  - node_modules
